# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  yarn:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0-stretch-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  deploy-prod:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to production
          command: |
            docker build -t mravinale/redirector:prod .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mravinale/redirector:prod

workflows:
  version: 2

  deploy-dev:
    jobs:
      - yarn
      - deploy-prod:
          requires:
            - yarn
          filters:
            branches:
              only: master
